name: boe-gpt

services:
  chroma:
    image: chromadb/chroma
    networks:
      - red
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  docs:
    build: ./boe_docs
    networks:
      - red
    ports:
      - "6550:6550"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6550/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      chroma:
        condition: service_healthy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  llm:
    build: ./boe_llm
    networks:
      - red
    ports:
      - "4550:4550"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4550/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  chain:
    build: ./boe_chain
    networks:
      - red
    ports:
      - "3550:3550"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3550/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      docs:
        condition: service_healthy
      llm:
        condition: service_healthy
  
  react:
    build: ./boe_react
    networks:
      - red
    ports:
      - "3000:3000"
    depends_on:
      chain:
        condition: service_healthy

networks:
  red:
    driver: bridge